spring:
  datasource:
    url: jdbc:mysql://mysqle84f3663d5f5.rds.ivolces.com:3306/sm_ai_manus?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: develop
    password: Xmzxl6706
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  ai:
    memory:
      mysql:
        enabled: true
  cloud:
    nacos:
      server-addr: intra-t-nacos.exexm.com:8848
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        namespace: dev
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
      config:
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
