spring:
  datasource:
    url: jdbc:mysql://rm-2ze148h4p2ywjovb2.mysql.rds.aliyuncs.com:3306/sm_cloud_ai_manus?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hotwheel
    password: cqmyg123!@#
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: false  # Disable SQL formatting in container environment for better performance
  ai:
    memory:
      mysql:
        enabled: true
  cloud:
    nacos:
      server-addr: intra-nacos.exexm.com:8848
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        namespace: prod
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
      config:
        namespace: prod
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml

manus:
  browser:
    headless: true
    requestTimeout: 180
  openBrowserAuto: false

logging:
  level:
    root: INFO
